//! Device-cleaner categories — BleachBit-style well-known cache and
//! junk locations that real-world cleanup tools target.
//!
//! All scanning is metadata-only. A cleaner category knows a set of
//! candidate paths on the current system; scanning one collects
//! `FileEntry` rows for everything under those paths so the result
//! flows straight into the existing Tidy plan pipeline.

use crate::scanner::{FileEntry, ScanOptions, Scanner};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// A pre-defined cleanup category.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CleanerCategory {
    UserCache,
    Thumbnails,
    Trash,
    TempFiles,
    SystemTempFiles,
    AptCache,
    AptLists,
    DnfCache,
    PacmanCache,
    FirefoxCache,
    ChromiumCache,
    ChromeCache,
    BashHistory,
    ZshHistory,
    RecentlyUsed,
    SystemLogs,
    JournalOld,
}

impl CleanerCategory {
    pub const ALL: &'static [CleanerCategory] = &[
        CleanerCategory::UserCache,
        CleanerCategory::Thumbnails,
        CleanerCategory::Trash,
        CleanerCategory::TempFiles,
        CleanerCategory::SystemTempFiles,
        CleanerCategory::AptCache,
        CleanerCategory::AptLists,
        CleanerCategory::DnfCache,
        CleanerCategory::PacmanCache,
        CleanerCategory::FirefoxCache,
        CleanerCategory::ChromiumCache,
        CleanerCategory::ChromeCache,
        CleanerCategory::BashHistory,
        CleanerCategory::ZshHistory,
        CleanerCategory::RecentlyUsed,
        CleanerCategory::SystemLogs,
        CleanerCategory::JournalOld,
    ];

    pub fn title(&self) -> &'static str {
        match self {
            CleanerCategory::UserCache => "User cache (~/.cache)",
            CleanerCategory::Thumbnails => "Thumbnail cache",
            CleanerCategory::Trash => "Trash bin",
            CleanerCategory::TempFiles => "User temp files",
            CleanerCategory::SystemTempFiles => "System temp files",
            CleanerCategory::AptCache => "APT package archives",
            CleanerCategory::AptLists => "APT repository lists",
            CleanerCategory::DnfCache => "DNF package cache",
            CleanerCategory::PacmanCache => "Pacman package cache",
            CleanerCategory::FirefoxCache => "Firefox cache",
            CleanerCategory::ChromiumCache => "Chromium cache",
            CleanerCategory::ChromeCache => "Chrome cache",
            CleanerCategory::BashHistory => "Bash history",
            CleanerCategory::ZshHistory => "Zsh history",
            CleanerCategory::RecentlyUsed => "Recently used files list",
            CleanerCategory::SystemLogs => "System log archives",
            CleanerCategory::JournalOld => "Old systemd journal",
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            CleanerCategory::UserCache => "Application caches under ~/.cache — usually safe to clear.",
            CleanerCategory::Thumbnails => "Image thumbnail previews generated by file managers.",
            CleanerCategory::Trash => "Files sent to the XDG trash bin.",
            CleanerCategory::TempFiles => "Transient files under ~/.tmp and ~/tmp.",
            CleanerCategory::SystemTempFiles => "/tmp and /var/tmp — used by running processes, clear with care.",
            CleanerCategory::AptCache => "Debian package archives in /var/cache/apt/archives.",
            CleanerCategory::AptLists => "Downloaded repository metadata in /var/lib/apt/lists.",
            CleanerCategory::DnfCache => "RPM package cache used by dnf/yum.",
            CleanerCategory::PacmanCache => "Arch pacman package cache.",
            CleanerCategory::FirefoxCache => "Firefox per-profile cache2 and startupCache directories.",
            CleanerCategory::ChromiumCache => "Chromium cache directories.",
            CleanerCategory::ChromeCache => "Google Chrome cache directories.",
            CleanerCategory::BashHistory => "~/.bash_history (leaves empty file).",
            CleanerCategory::ZshHistory => "~/.zsh_history and histfile.",
            CleanerCategory::RecentlyUsed => "~/.local/share/recently-used.xbel.",
            CleanerCategory::SystemLogs => "Rotated log archives in /var/log/*.gz, *.1, *.old.",
            CleanerCategory::JournalOld => "systemd journal files older than a week in /var/log/journal.",
        }
    }

    pub fn destructive_note(&self) -> Option<&'static str> {
        match self {
            CleanerCategory::SystemTempFiles => Some("May interrupt running apps with files in /tmp."),
            CleanerCategory::AptLists => Some("apt update will need to re-download metadata."),
            CleanerCategory::BashHistory | CleanerCategory::ZshHistory => {
                Some("Shell history will be erased — can impact recall.")
            }
            _ => None,
        }
    }

    /// Candidate root paths for this category. Existence is not checked.
    pub fn candidate_paths(&self, home: Option<&Path>) -> Vec<PathBuf> {
        let home = home.map(|h| h.to_path_buf());
        match self {
            CleanerCategory::UserCache => home.iter().map(|h| h.join(".cache")).collect(),
            CleanerCategory::Thumbnails => home
                .iter()
                .map(|h| h.join(".cache").join("thumbnails"))
                .collect(),
            CleanerCategory::Trash => home
                .iter()
                .map(|h| h.join(".local").join("share").join("Trash"))
                .collect(),
            CleanerCategory::TempFiles => home
                .iter()
                .flat_map(|h| {
                    vec![
                        h.join(".tmp"),
                        h.join("tmp"),
                        h.join(".local").join("tmp"),
                    ]
                })
                .collect(),
            CleanerCategory::SystemTempFiles => vec![PathBuf::from("/tmp"), PathBuf::from("/var/tmp")],
            CleanerCategory::AptCache => vec![PathBuf::from("/var/cache/apt/archives")],
            CleanerCategory::AptLists => vec![PathBuf::from("/var/lib/apt/lists")],
            CleanerCategory::DnfCache => vec![PathBuf::from("/var/cache/dnf"), PathBuf::from("/var/cache/yum")],
            CleanerCategory::PacmanCache => vec![PathBuf::from("/var/cache/pacman/pkg")],
            CleanerCategory::FirefoxCache => home
                .iter()
                .flat_map(|h| {
                    vec![
                        h.join(".mozilla").join("firefox"),
                        h.join(".cache").join("mozilla").join("firefox"),
                    ]
                })
                .collect(),
            CleanerCategory::ChromiumCache => home
                .iter()
                .flat_map(|h| {
                    vec![
                        h.join(".cache").join("chromium"),
                        h.join(".config").join("chromium").join("Default").join("Cache"),
                    ]
                })
                .collect(),
            CleanerCategory::ChromeCache => home
                .iter()
                .flat_map(|h| {
                    vec![
                        h.join(".cache").join("google-chrome"),
                        h.join(".config").join("google-chrome").join("Default").join("Cache"),
                    ]
                })
                .collect(),
            CleanerCategory::BashHistory => home.iter().map(|h| h.join(".bash_history")).collect(),
            CleanerCategory::ZshHistory => home
                .iter()
                .flat_map(|h| vec![h.join(".zsh_history"), h.join(".histfile")])
                .collect(),
            CleanerCategory::RecentlyUsed => home
                .iter()
                .map(|h| h.join(".local").join("share").join("recently-used.xbel"))
                .collect(),
            CleanerCategory::SystemLogs => vec![PathBuf::from("/var/log")],
            CleanerCategory::JournalOld => vec![PathBuf::from("/var/log/journal")],
        }
    }

    /// True if the category expects a glob filter beyond simple recursion
    /// (e.g. System logs only wants rotated archives, not live logs).
    pub fn file_filter(&self, path: &Path) -> bool {
        match self {
            CleanerCategory::SystemLogs => {
                let name = path
                    .file_name()
                    .and_then(|s| s.to_str())
                    .unwrap_or_default();
                name.ends_with(".gz")
                    || name.ends_with(".1")
                    || name.ends_with(".old")
                    || name.ends_with(".zst")
            }
            _ => true,
        }
    }
}

/// Result of scanning one cleaner category.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CleanerReport {
    pub category: CleanerCategory,
    pub files_found: usize,
    pub total_bytes: u64,
    pub entries: Vec<FileEntry>,
    pub candidate_paths: Vec<PathBuf>,
    pub missing_paths: Vec<PathBuf>,
}

impl CleanerReport {
    pub fn empty(category: CleanerCategory) -> Self {
        Self {
            category,
            files_found: 0,
            total_bytes: 0,
            entries: Vec::new(),
            candidate_paths: Vec::new(),
            missing_paths: Vec::new(),
        }
    }
}

/// Scan a single cleaner category. Returns aggregate stats and the
/// full list of file entries under its candidate paths.
pub fn scan_category(category: CleanerCategory) -> CleanerReport {
    let home = std::env::var_os("HOME").map(PathBuf::from);
    let candidates = category.candidate_paths(home.as_deref());
    let mut entries = Vec::new();
    let mut missing = Vec::new();
    let mut total = 0u64;

    for root in &candidates {
        if !root.exists() {
            missing.push(root.clone());
            continue;
        }
        if root.is_file() {
            if let Ok(meta) = std::fs::metadata(root) {
                let entry = FileEntry::from_metadata(root.clone(), &meta);
                total += entry.size;
                entries.push(entry);
            }
            continue;
        }

        let mut scanner = Scanner::new(ScanOptions {
            include_hidden: true,
            skip_mounts: true,
            follow_symlinks: false,
            max_depth: None,
            min_size: 0,
        });
        if scanner.scan(root).is_err() {
            continue;
        }
        for e in scanner.into_entries() {
            if !category.file_filter(&e.path) {
                continue;
            }
            total += e.size;
            entries.push(e);
        }
    }

    CleanerReport {
        category,
        files_found: entries.len(),
        total_bytes: total,
        entries,
        candidate_paths: candidates,
        missing_paths: missing,
    }
}

/// Scan every built-in category and return one report per category.
pub fn scan_all() -> Vec<CleanerReport> {
    CleanerCategory::ALL.iter().map(|c| scan_category(*c)).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_categories_have_titles() {
        for cat in CleanerCategory::ALL {
            assert!(!cat.title().is_empty(), "{:?} missing title", cat);
        }
    }

    #[test]
    fn test_all_categories_have_descriptions() {
        for cat in CleanerCategory::ALL {
            assert!(!cat.description().is_empty(), "{:?} missing desc", cat);
        }
    }

    #[test]
    fn test_candidate_paths_non_empty_with_home() {
        let home = Path::new("/home/test");
        for cat in CleanerCategory::ALL {
            let paths = cat.candidate_paths(Some(home));
            assert!(!paths.is_empty(), "{:?} has no candidates", cat);
        }
    }

    #[test]
    fn test_apt_cache_is_absolute() {
        let paths = CleanerCategory::AptCache.candidate_paths(None);
        assert_eq!(paths[0], PathBuf::from("/var/cache/apt/archives"));
    }

    #[test]
    fn test_thumbnails_uses_home() {
        let paths = CleanerCategory::Thumbnails.candidate_paths(Some(Path::new("/home/x")));
        assert_eq!(
            paths[0],
            PathBuf::from("/home/x/.cache/thumbnails")
        );
    }

    #[test]
    fn test_system_logs_filter_accepts_rotated() {
        let cat = CleanerCategory::SystemLogs;
        assert!(cat.file_filter(Path::new("/var/log/syslog.1")));
        assert!(cat.file_filter(Path::new("/var/log/kern.log.gz")));
        assert!(!cat.file_filter(Path::new("/var/log/syslog")));
    }

    #[test]
    fn test_other_categories_accept_any_file() {
        assert!(CleanerCategory::UserCache.file_filter(Path::new("/x/y")));
    }

    #[test]
    fn test_destructive_note_optional() {
        assert!(CleanerCategory::SystemTempFiles.destructive_note().is_some());
        assert!(CleanerCategory::UserCache.destructive_note().is_none());
    }

    #[test]
    fn test_scan_category_missing_paths_ok() {
        // Just verify scan_category doesn't panic on categories whose
        // candidate paths may not exist on the current host.
        let report = scan_category(CleanerCategory::PacmanCache);
        // On a non-Arch system, the pacman cache doesn't exist, so
        // missing_paths should contain the candidate.
        assert!(!report.missing_paths.is_empty() || !report.entries.is_empty());
    }

    #[test]
    fn test_scan_all_returns_all_categories() {
        let reports = scan_all();
        assert_eq!(reports.len(), CleanerCategory::ALL.len());
    }
}
